version: '3'

services:

  dynamodb:
    image: lambda-template/dynamodb
    container_name: lambda-template-dynamodb
    build:
      context: ./dynamodb
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - lambda-template-dynamodb-store:/home/dynamodblocal/data
    command: -jar DynamoDBLocal.jar -dbPath ./data

  awscli:
    image: lambda-template/awscli
    container_name: lambda-template-awscli
    build:
      context: ./awscli
      dockerfile: Dockerfile
    tty: true
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
    volumes:
      - ../:/aws
    working_dir: /aws
    depends_on:
      - dynamodb

volumes:
  lambda-template-dynamodb-store:
