version: '3'

services:

  dynamodb:
    image: lambda-template/dynamodb
    container_name: lambda-template-dynamodb
    build:
      context: ./dynamodb
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - lambda-template-dynamodb-store:/home/dynamodblocal/data
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    networks:
      - lambda-local

  dynamodb-admin:
    container_name: lambda-template-dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
    networks:
      - lambda-local

  console:
    image: lambda-template/console
    container_name: lambda-template-console
    build:
      context: ./console
      dockerfile: Dockerfile
    tty: true
    environment:
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
    volumes:
      - ../:/app
    networks:
      - lambda-local

  app:
    image: lambda-template/console
    container_name: lambda-template-app
    build:
      context: ./console
      dockerfile: Dockerfile
    tty: true
    restart: always
    volumes:
      - ../app/:/app
    ports:
      - 3000:3000
    networks: 
      - lambda-local
    command: /bin/bash -c "npm run dev"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: lambda-template-mailhog
    ports:
      - 8025:8025
      - 25:1025
    networks:
      - lambda-local

volumes:
  lambda-template-dynamodb-store:

networks:
  lambda-local:
    external: true